### ISSUE TITLE
Asegurarse de que cada botón en la documentación funcione correctamente.

### ISSUE THREAD

**Issue by Abiu77** [SENATI-ASSISTENT/docs-senati#64]

**Comment by myasis** [comment]
- En la documentación encontré que el botón de "Editar una página" no funciona, ya que manda un error 404, 'not found'.
Pero la mayoría de botones si funciona.
<img width="775" alt="Captura de pantalla 2024-09-19 a las 10 10 13 p  m" src="https://github.com/user-attachments/assets/75f09e61-1956-4e15-8c07-8c0ae742e053">
